---
title: "Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of Total Number of Orders vs. Order Hour of Day by Department

```{r}
dept_hour_df = instacart |> 
  group_by(department, order_hour_of_day) |> 
  filter(!is.na(department) & !is.na(order_hour_of_day)) |> 
  summarize(total_orders = n())

dept_hour_df |> 
  plot_ly(x = ~order_hour_of_day, 
          y = ~total_orders, 
          color = ~department,
          type = "scatter",
          mode = "lines")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Bar chart of the top 15 most ordered products

```{r}
instacart |>
  count(product_name, sort = TRUE) |>
  slice_head(n = 15) |>
  plot_ly(
    x = ~reorder(product_name, n),
    y = ~n,
    type = "bar",
    orientation = "v"
  ) |>
  layout(
    title = "Top 15 Most Ordered Products",
    xaxis = list(title = "Product"),
    yaxis = list(title = "Orders")
  )
```

### Box plot distributions of Add-to-Cart Orders by Department

```{r}
top10_depts = instacart |>
  count(department, sort = TRUE) |>
  slice_head(n = 10) |>
  pull(department)

instacart |> 
  filter(department %in% top10_depts) |>
  plot_ly(
    x = ~department,
    y = ~add_to_cart_order,
    color = ~department,
    type = "box",
    boxpoints = "outliers",
    marker = list(opacity = 0.4),
    line = list(width = 1)
  ) |>
  layout(
    title = "Add-to-Cart Order by Department (Top 10)",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Add-to-Cart Position")
  )
```

